### ISSUE TITLE
Proper delete

### ISSUE THREAD

**Issue by helsted** [camunda/camunda-bpm-mail#16] opened 2018-11-09 15:26 UTC
After deleting mails folder.close(true) should be issued to ensure that messages get expunged.

**Comment by edmondo1984** [comment] 2019-03-28 17:02
Does actually deletion work? It is not working for me

**Comment by saig0** [comment] 2020-05-12 13:26
It should be fixed in version 1.3.0. 

Please re-open the issue if the problem is still present.

**Closed by saig0** 2020-05-12 13:26 UTC
Labels: enhancement
